module.exports = require("!espruino-loader!espruino/espruino.js")
require("!espruino-loader!espruino/core/utils.js")
require("!espruino-loader!espruino/core/config.js")
require("!espruino-loader!espruino/core/serial.js")
require("!espruino-loader!espruino/core/serial_web_bluetooth.js")
require("!espruino-loader!espruino/core/codeWriter.js")
require("!espruino-loader!espruino/core/flasher.js")
require("!espruino-loader!espruino/plugins/getGitHub.js")
require("!espruino-loader!espruino/plugins/unicode.js")
require("!espruino-loader!espruino/plugins/minify.js")
require("!espruino-loader!espruino/plugins/pretokenise.js")
