name: Approve Build User

on:
  issue_comment:
    types: [created]

jobs:
  approve-build-user:
    if: >
      github.event.issue.pull_request != null &&
      github.event.comment.body == 'Approve build user' &&
      (github.event.comment.author_association == 'OWNER' ||
       github.event.comment.author_association == 'COLLABORATOR' ||
       github.event.comment.author_association == 'MEMBER')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout default branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.repository.default_branch }}

      - name: Set PR creator ID environment variable
        run: echo "PR_CREATOR_ID=${{ github.event.issue.user.id }}" >> $GITHUB_ENV

      - name: Set commenter ID environment variable
        run: echo "COMMENTER_ID=${{ github.event.comment.user.id }}" >> $GITHUB_ENV

      - name: Update approved-users.json
        run: |
          FILE=".github/approved-users.json"
          PR_ID=$PR_CREATOR_ID
          if [ -f "$FILE" ]; then
            echo "File exists. Checking if user ID $PR_ID is already approved..."
            if jq -e ". | index($PR_ID)" "$FILE" > /dev/null; then
              echo "User ID $PR_ID is already approved."
            else
              echo "Appending user ID $PR_ID."
              TMP=$(mktemp)
              jq ". + [$PR_ID]" "$FILE" > "$TMP"
              mv "$TMP" "$FILE"
            fi
          else
            echo "File does not exist. Creating file with user ID $PR_ID..."
            mkdir -p $(dirname "$FILE")
            echo "[$PR_ID]" | jq . > "$FILE"
          fi

      - name: Commit and push changes
        run: |
          # Configure git using the comment's actor information,
          # including the comment user id in the email.
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}+${COMMENTER_ID}@users.noreply.github.com"
          git add .github/approved-users.json
          git commit -m "Update approved users with PR creator ID ${PR_CREATOR_ID}" || echo "No changes to commit"
          git push
