name: Trigger Build and Deploy Workflow

on:
  push:
    branches-ignore:
      - master
  workflow_dispatch:

jobs:
  trigger-nodejs-workflow:
    permissions:
      contents: read
      actions: write  # Ensure the token can trigger workflows

    runs-on: ubuntu-latest

    steps:
      - name: Trigger build workflow if pushed to any branch other than master
        run: |
          # Trigger the node.js.yml workflow via GitHub API using curl
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d '{"ref": "master"}' \
            "https://api.github.com/repos/${{ github.repository }}/actions/workflows/node.js.yml/dispatches"
